import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type Language = 'en' | 'te' | 'hi' | 'ml' | 'kn'
const KEY = 'gymai_language'

type Dictionary = Record<string, string>
const base: Dictionary = {
  Home:'Home', Dashboard:'Dashboard', Workout:'Workout', Exercises:'Exercises', Progress:'Progress', History:'History', Profile:'Profile', Settings:'Settings', Equipment:'Equipment', About:'About',
  'About GymAI':'About GymAI', 'Sign in':'Sign in', 'Start my plan':'Start my plan', 'AI Training':'AI Training', 'Exercise Library':'Exercise Library', 'Member Stories':'Member Stories', 'Form Feedback':'Form Feedback', Language:'Language', English:'English', Telugu:'Telugu', Hindi:'Hindi', Malayalam:'Malayalam', Kannada:'Kannada',
  'View Demo':'View Demo','View Me':'View Me',Close:'Close',Sets:'Sets',Reps:'Reps',Rest:'Rest','Form cues':'Form cues','Common mistakes':'Common mistakes','Exercise video':'Exercise video','Workout plan':'Workout plan',Next:'Next',Pause:'Pause','Start timer':'Start timer',Stop:'Stop',Lap:'Lap',Reset:'Reset',Alarm:'Alarm',Beginner:'Beginner',Intermediate:'Intermediate',Advanced:'Advanced',Amazon:'Amazon',Flipkart:'Flipkart','Buy on Amazon':'Buy on Amazon','Buy on Flipkart':'Buy on Flipkart',Motivation:'Motivation',
  Exercise:'Exercise',exercises:'exercises',sets:'sets',reps:'reps',of:'of',min:'min','minutes recorded':'minutes recorded','exercise demonstration':'exercise demonstration','Set progress':'Set progress','Start AI form check':'Start AI form check','Run AI form check':'Run AI form check','Exercise complete':'Exercise complete','Complete set':'Complete set','AI form check saved':'AI form check saved',form:'form','Select a level and watch the exercise demo.':'Select a level and watch the exercise demo.','Beginner AI form support':'Beginner AI form support','This movement is prepared for the MediaPipe training flow.':'This movement is prepared for the MediaPipe training flow.',
  'Unable to load your workout.':'Unable to load your workout.',"Your workout isn't ready yet.":"Your workout isn't ready yet.",'Complete your training profile so GymAI can select exercises from your available equipment.':'Complete your training profile so GymAI can select exercises from your available equipment.','GymAI needs your fitness level, goal, and equipment before it can build a personalized workout.':'GymAI needs your fitness level, goal, and equipment before it can build a personalized workout.','Complete profile':'Complete profile','Workout complete':'Workout complete','Back to dashboard':'Back to dashboard','Workout saved to your training history.':'Workout saved to your training history.','Workout could not be saved. Please try again.':'Workout could not be saved. Please try again.','The timer keeps counting across refreshes and when you leave the site. It stops only when you press Stop or Reset.':'The timer keeps counting across refreshes and when you leave the site. It stops only when you press Stop or Reset.',
  None:'None',Bodyweight:'Bodyweight',Dumbbell:'Dumbbell',Barbell:'Barbell',Machine:'Machine',Cable:'Cable',Kettlebell:'Kettlebell',Bands:'Bands','Full Gym':'Full Gym',Chest:'Chest',Back:'Back',Legs:'Legs',Shoulders:'Shoulders',Arms:'Arms',Core:'Core','Full Body':'Full Body',Triceps:'Triceps',Biceps:'Biceps',Quads:'Quads',Glutes:'Glutes',Hamstrings:'Hamstrings',Today:'Today',Tomorrow:'Tomorrow',Thursday:'Thursday',Saturday:'Saturday','General fitness':'General fitness','Fat Loss':'Fat Loss','Muscle Building':'Muscle Building',Strength:'Strength','Finish workout':'Finish workout','YouTube':'YouTube','View exercise video':'View exercise video','No video available':'No video available',
}
const translations: Record<Language, Dictionary> = { en: base,
 te: {...base, Home:'హోమ్',Dashboard:'డ్యాష్‌బోర్డ్',Workout:'వర్కౌట్',Exercises:'వ్యాయామాలు',Progress:'పురోగతి',History:'చరిత్ర',Profile:'ప్రొఫైల్',Settings:'సెట్టింగ్స్',Equipment:'పరికరాలు',About:'మా గురించి','About GymAI':'GymAI గురించి','Sign in':'సైన్ ఇన్','Start my plan':'నా ప్లాన్ ప్రారంభించండి','AI Training':'AI శిక్షణ','Exercise Library':'వ్యాయామ లైబ్రరీ','Member Stories':'సభ్యుల కథలు','Form Feedback':'ఫారమ్ ఫీడ్‌బ్యాక్',Language:'భాష',English:'ఇంగ్లీష్',Telugu:'తెలుగు',Hindi:'హిందీ',Malayalam:'మలయాళం',Kannada:'కన్నడ','View Demo':'డెమో చూడండి','View Me':'చూడండి',Close:'మూసివేయి',Sets:'సెట్లు',Reps:'రెప్స్',Rest:'విరామం','Form cues':'ఫారమ్ సూచనలు','Common mistakes':'సాధారణ తప్పులు','Exercise video':'వ్యాయామ వీడియో','Workout plan':'వర్కౌట్ ప్లాన్',Next:'తదుపరి',Pause:'పాజ్','Start timer':'టైమర్ ప్రారంభించండి',Stop:'ఆపు',Lap:'ల్యాప్',Reset:'రీసెట్',Alarm:'అలారం',Beginner:'బిగినర్',Intermediate:'ఇంటర్మీడియట్',Advanced:'అడ్వాన్స్‌డ్',Amazon:'అమెజాన్',Flipkart:'ఫ్లిప్‌కార్ట్','Buy on Amazon':'అమెజాన్‌లో చూడండి','Buy on Flipkart':'ఫ్లిప్‌కార్ట్‌లో చూడండి',Motivation:'ప్రేరణ',Exercise:'వ్యాయామం',exercises:'వ్యాయామాలు',sets:'సెట్లు',reps:'రెప్స్',of:'లో',min:'నిమి','minutes recorded':'నిమిషాలు నమోదు చేయబడ్డాయి','exercise demonstration':'వ్యాయామ ప్రదర్శన','Set progress':'సెట్ పురోగతి','Start AI form check':'AI ఫారమ్ చెక్ ప్రారంభించండి','Run AI form check':'AI ఫారమ్ చెక్ చేయండి','Exercise complete':'వ్యాయామం పూర్తయింది','Complete set':'సెట్ పూర్తి చేయండి','AI form check saved':'AI ఫారమ్ చెక్ సేవ్ చేయబడింది',form:'ఫారమ్',None:'ఏదీ లేదు',Bodyweight:'శరీర బరువు',Dumbbell:'డంబెల్',Barbell:'బార్బెల్',Machine:'మెషిన్',Cable:'కేబుల్',Kettlebell:'కెటిల్‌బెల్',Bands:'బ్యాండ్స్','Full Gym':'పూర్తి జిమ్',Chest:'ఛాతీ',Back:'వెనుక',Legs:'కాళ్లు',Shoulders:'భుజాలు',Arms:'చేతులు',Core:'కోర్','Full Body':'పూర్తి శరీరం',Triceps:'ట్రైసెప్స్',Biceps:'బైసెప్స్',Quads:'క్వాడ్స్',Glutes:'గ్లూట్స్',Hamstrings:'హ్యామ్‌స్ట్రింగ్స్',Today:'ఈ రోజు',Tomorrow:'రేపు',Thursday:'గురువారం',Saturday:'శనివారం','General fitness':'సాధారణ ఫిట్‌నెస్','Fat Loss':'కొవ్వు తగ్గింపు','Muscle Building':'కండరాల నిర్మాణం',Strength:'బలం','Finish workout':'వర్కౌట్ ముగించండి','YouTube':'యూట్యూబ్','View exercise video':'వ్యాయామ వీడియో చూడండి','No video available':'వీడియో అందుబాటులో లేదు','Complete profile':'ప్రొఫైల్ పూర్తి చేయండి','Workout complete':'వర్కౌట్ పూర్తయింది','Back to dashboard':'డ్యాష్‌బోర్డ్‌కు తిరిగి వెళ్లండి'},
 hi: {...base,Home:'होम',Dashboard:'डैशबोर्ड',Workout:'वर्कआउट',Exercises:'व्यायाम',Progress:'प्रगति',History:'इतिहास',Profile:'प्रोफ़ाइल',Settings:'सेटिंग्स',Equipment:'उपकरण',About:'हमारे बारे में','About GymAI':'GymAI के बारे में','Sign in':'साइन इन','Start my plan':'मेरा प्लान शुरू करें','AI Training':'AI ट्रेनिंग','Exercise Library':'व्यायाम लाइब्रेरी','Member Stories':'सदस्यों की कहानियाँ','Form Feedback':'फॉर्म फीडबैक',Language:'भाषा',English:'अंग्रेज़ी',Telugu:'तेलुगु',Hindi:'हिंदी',Malayalam:'मलयालम',Kannada:'कन्नड़','View Demo':'डेमो देखें','View Me':'देखें',Close:'बंद करें',Sets:'सेट्स',Reps:'रेप्स',Rest:'आराम','Form cues':'फॉर्म संकेत','Common mistakes':'आम गलतियाँ','Exercise video':'व्यायाम वीडियो','Workout plan':'वर्कआउट प्लान',Next:'अगला',Pause:'रोकें','Start timer':'टाइमर शुरू करें',Stop:'रोकें',Lap:'लैप',Reset:'रीसेट',Alarm:'अलार्म',Beginner:'शुरुआती',Intermediate:'मध्यम',Advanced:'उन्नत',Amazon:'अमेज़न',Flipkart:'फ्लिपकार्ट',Exercise:'व्यायाम',exercises:'व्यायाम',sets:'सेट्स',reps:'रेप्स',of:'में से',min:'मिनट','minutes recorded':'मिनट दर्ज','exercise demonstration':'व्यायाम प्रदर्शन','Set progress':'सेट प्रगति','Start AI form check':'AI फॉर्म चेक शुरू करें','Run AI form check':'AI फॉर्म चेक चलाएँ','Exercise complete':'व्यायाम पूरा हुआ','Complete set':'सेट पूरा करें','AI form check saved':'AI फॉर्म चेक सेव हुआ',form:'फॉर्म',None:'कोई नहीं',Bodyweight:'बॉडीवेट',Dumbbell:'डम्बल',Barbell:'बारबेल',Machine:'मशीन',Cable:'केबल',Kettlebell:'केटलबेल',Bands:'बैंड्स','Full Gym':'पूरा जिम',Chest:'छाती',Back:'पीठ',Legs:'पैर',Shoulders:'कंधे',Arms:'बांहें',Core:'कोर','Full Body':'पूरा शरीर',Triceps:'ट्राइसेप्स',Biceps:'बाइसेप्स',Quads:'क्वाड्स',Glutes:'ग्लूट्स',Hamstrings:'हैमस्ट्रिंग्स',Today:'आज',Tomorrow:'कल',Thursday:'गुरुवार',Saturday:'शनिवार','General fitness':'सामान्य फिटनेस','Fat Loss':'वसा कम करना','Muscle Building':'मांसपेशियों का निर्माण',Strength:'ताकत','Finish workout':'वर्कआउट समाप्त करें','YouTube':'यूट्यूब','View exercise video':'व्यायाम वीडियो देखें','No video available':'वीडियो उपलब्ध नहीं है','Complete profile':'प्रोफ़ाइल पूरा करें','Workout complete':'वर्कआउट पूरा हुआ','Back to dashboard':'डैशबोर्ड पर वापस जाएँ'},
 ml: {...base,Home:'ഹോം',Dashboard:'ഡാഷ്ബോർഡ്',Workout:'വർക്ക്ഔട്ട്',Exercises:'വ്യായാമങ്ങൾ',Progress:'പുരോഗതി',History:'ചരിത്രം',Profile:'പ്രൊഫൈൽ',Settings:'ക്രമീകരണങ്ങൾ',Equipment:'ഉപകരണങ്ങൾ',About:'ഞങ്ങളെക്കുറിച്ച്','About GymAI':'GymAIയെക്കുറിച്ച്','Sign in':'സൈൻ ഇൻ','Start my plan':'എന്റെ പ്ലാൻ ആരംഭിക്കുക','AI Training':'AI പരിശീലനം','Exercise Library':'വ്യായാമ ലൈബ്രറി','Member Stories':'അംഗങ്ങളുടെ കഥകൾ','Form Feedback':'ഫോം ഫീഡ്ബാക്ക്',Language:'ഭാഷ',English:'ഇംഗ്ലീഷ്',Telugu:'തെലുങ്ക്',Hindi:'ഹിന്ദി',Malayalam:'മലയാളം',Kannada:'കന്നഡ','View Demo':'ഡെമോ കാണുക','View Me':'കാണുക',Close:'അടയ്ക്കുക',Sets:'സെറ്റുകൾ',Reps:'റെപ്സ്',Rest:'വിശ്രമം','Form cues':'ഫോം നിർദ്ദേശങ്ങൾ','Common mistakes':'സാധാരണ പിഴവുകൾ','Exercise video':'വ്യായാമ വീഡിയോ','Workout plan':'വർക്ക്ഔട്ട് പ്ലാൻ',Next:'അടുത്തത്',Pause:'താൽക്കാലികമായി നിർത്തുക','Start timer':'ടൈമർ ആരംഭിക്കുക',Stop:'നിർത്തുക',Lap:'ലാപ്',Reset:'റീസെറ്റ്',Alarm:'അലാറം',Beginner:'തുടക്കക്കാർ',Intermediate:'ഇന്റർമീഡിയറ്റ്',Advanced:'അഡ്വാൻസ്ഡ്',Amazon:'ആമസോൺ',Flipkart:'ഫ്ലിപ്കാർട്ട്',Exercise:'വ്യായാമം',exercises:'വ്യായാമങ്ങൾ',sets:'സെറ്റുകൾ',reps:'റെപ്സ്',of:'ൽ',min:'മിനിറ്റ്','minutes recorded':'മിനിറ്റുകൾ രേഖപ്പെടുത്തി','exercise demonstration':'വ്യായാമ പ്രദർശനം','Set progress':'സെറ്റ് പുരോഗതി','Start AI form check':'AI ഫോം ചെക്ക് ആരംഭിക്കുക','Run AI form check':'AI ഫോം ചെക്ക് നടത്തുക','Exercise complete':'വ്യായാമം പൂർത്തിയായി','Complete set':'സെറ്റ് പൂർത്തിയാക്കുക','AI form check saved':'AI ഫോം ചെക്ക് സംരക്ഷിച്ചു',form:'ഫോം',None:'ഒന്നുമില്ല',Bodyweight:'ശരീരഭാരം',Dumbbell:'ഡംബെൽ',Barbell:'ബാർബെൽ',Machine:'മെഷീൻ',Cable:'കേബിൾ',Kettlebell:'കെറ്റിൽബെൽ',Bands:'ബാൻഡുകൾ','Full Gym':'പൂർണ്ണ ജിം',Chest:'നെഞ്ച്',Back:'പുറം',Legs:'കാലുകൾ',Shoulders:'തോളുകൾ',Arms:'കൈകൾ',Core:'കോർ','Full Body':'പൂർണ്ണ ശരീരം',Triceps:'ട്രൈസെപ്സ്',Biceps:'ബൈസെപ്സ്',Quads:'ക്വാഡ്സ്',Glutes:'ഗ്ലൂട്ട്സ്',Hamstrings:'ഹാംസ്ട്രിംഗ്സ്',Today:'ഇന്ന്',Tomorrow:'നാളെ',Thursday:'വ്യാഴാഴ്ച',Saturday:'ശനിയാഴ്ച','General fitness':'പൊതുവായ ഫിറ്റ്നസ്','Fat Loss':'കൊഴുപ്പ് കുറയ്ക്കൽ','Muscle Building':'പേശി നിർമ്മാണം',Strength:'ശക്തി','Finish workout':'വർക്ക്ഔട്ട് പൂർത്തിയാക്കുക','YouTube':'യൂട്യൂബ്','View exercise video':'വ്യായാമ വീഡിയോ കാണുക','No video available':'വീഡിയോ ലഭ്യമല്ല','Complete profile':'പ്രൊഫൈൽ പൂർത്തിയാക്കുക','Workout complete':'വർക്ക്ഔട്ട് പൂർത്തിയായി','Back to dashboard':'ഡാഷ്ബോർഡിലേക്ക് മടങ്ങുക'},
 kn: {...base,Home:'ಮುಖಪುಟ',Dashboard:'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',Workout:'ವರ್ಕೌಟ್',Exercises:'ವ್ಯಾಯಾಮಗಳು',Progress:'ಪ್ರಗತಿ',History:'ಇತಿಹಾಸ',Profile:'ಪ್ರೊಫೈಲ್',Settings:'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',Equipment:'ಉಪಕರಣಗಳು',About:'ನಮ್ಮ ಬಗ್ಗೆ','About GymAI':'GymAI ಬಗ್ಗೆ','Sign in':'ಸೈನ್ ಇನ್','Start my plan':'ನನ್ನ ಪ್ಲಾನ್ ಆರಂಭಿಸಿ','AI Training':'AI ತರಬೇತಿ','Exercise Library':'ವ್ಯಾಯಾಮ ಲೈಬ್ರರಿ','Member Stories':'ಸದಸ್ಯರ ಕಥೆಗಳು','Form Feedback':'ಫಾರ್ಮ್ ಪ್ರತಿಕ್ರಿಯೆ',Language:'ಭಾಷೆ',English:'ಇಂಗ್ಲಿಷ್',Telugu:'ತೆಲುಗು',Hindi:'ಹಿಂದಿ',Malayalam:'ಮಲಯಾಳಂ',Kannada:'ಕನ್ನಡ','View Demo':'ಡೆಮೋ ನೋಡಿ','View Me':'ನೋಡಿ',Close:'ಮುಚ್ಚಿ',Sets:'ಸೆಟ್‌ಗಳು',Reps:'ರೆಪ್ಸ್',Rest:'ವಿಶ್ರಾಂತಿ','Form cues':'ಫಾರ್ಮ್ ಸೂಚನೆಗಳು','Common mistakes':'ಸಾಮಾನ್ಯ ತಪ್ಪುಗಳು','Exercise video':'ವ್ಯಾಯಾಮ ವೀಡಿಯೊ','Workout plan':'ವರ್ಕೌಟ್ ಪ್ಲಾನ್',Next:'ಮುಂದೆ',Pause:'ವಿರಾಮ','Start timer':'ಟೈಮರ್ ಪ್ರಾರಂಭಿಸಿ',Stop:'ನಿಲ್ಲಿಸಿ',Lap:'ಲ್ಯಾಪ್',Reset:'ರೀಸೆಟ್',Alarm:'ಅಲಾರಂ',Beginner:'ಆರಂಭಿಕ',Intermediate:'ಮಧ್ಯಮ',Advanced:'ಮುನ್ನಡೆದ',Amazon:'ಅಮೆಜಾನ್',Flipkart:'ಫ್ಲಿಪ್‌ಕಾರ್ಟ್',Exercise:'ವ್ಯಾಯಾಮ',exercises:'ವ್ಯಾಯಾಮಗಳು',sets:'ಸೆಟ್‌ಗಳು',reps:'ರೆಪ್ಸ್',of:'ರಲ್ಲಿ',min:'ನಿಮಿಷ','minutes recorded':'ನಿಮಿಷ ದಾಖಲಾಗಿದೆ','exercise demonstration':'ವ್ಯಾಯಾಮ ಪ್ರದರ್ಶನ','Set progress':'ಸೆಟ್ ಪ್ರಗತಿ','Start AI form check':'AI ಫಾರ್ಮ್ ಚೆಕ್ ಆರಂಭಿಸಿ','Run AI form check':'AI ಫಾರ್ಮ್ ಚೆಕ್ ನಡೆಸಿ','Exercise complete':'ವ್ಯಾಯಾಮ ಪೂರ್ಣಗೊಂಡಿದೆ','Complete set':'ಸೆಟ್ ಪೂರ್ಣಗೊಳಿಸಿ','AI form check saved':'AI ಫಾರ್ಮ್ ಚೆಕ್ ಉಳಿಸಲಾಗಿದೆ',form:'ಫಾರ್ಮ್',None:'ಯಾವುದೂ ಇಲ್ಲ',Bodyweight:'ದೇಹದ ತೂಕ',Dumbbell:'ಡಂಬೆಲ್',Barbell:'ಬಾರ್ಬೆಲ್',Machine:'ಮೆಷಿನ್',Cable:'ಕೇಬಲ್',Kettlebell:'ಕೆಟಲ್‌ಬೆಲ್',Bands:'ಬ್ಯಾಂಡ್ಸ್','Full Gym':'ಪೂರ್ಣ ಜಿಮ್',Chest:'ಎದೆ',Back:'ಬೆನ್ನು',Legs:'ಕಾಲುಗಳು',Shoulders:'ಭುಜಗಳು',Arms:'ತೋಳುಗಳು',Core:'ಕೋರ್','Full Body':'ಪೂರ್ಣ ದೇಹ',Triceps:'ಟ್ರೈಸೆಪ್ಸ್',Biceps:'ಬೈಸೆಪ್ಸ್',Quads:'ಕ್ವಾಡ್ಸ್',Glutes:'ಗ್ಲೂಟ್ಸ್',Hamstrings:'ಹ್ಯಾಮ್‌ಸ್ಟ್ರಿಂಗ್ಸ್',Today:'ಇಂದು',Tomorrow:'ನಾಳೆ',Thursday:'ಗುರುವಾರ',Saturday:'ಶನಿವಾರ','General fitness':'ಸಾಮಾನ್ಯ ಫಿಟ್ನೆಸ್','Fat Loss':'ಕೊಬ್ಬು ಕಡಿತ','Muscle Building':'ಸ್ನಾಯು ನಿರ್ಮಾಣ',Strength:'ಬಲ','Finish workout':'ವರ್ಕೌಟ್ ಮುಗಿಸಿ','YouTube':'ಯೂಟ್ಯೂಬ್','View exercise video':'ವ್ಯಾಯಾಮ ವೀಡಿಯೊ ನೋಡಿ','No video available':'ವೀಡಿಯೊ ಲಭ್ಯವಿಲ್ಲ','Complete profile':'ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ','Workout complete':'ವರ್ಕೌಟ್ ಪೂರ್ಣಗೊಂಡಿದೆ','Back to dashboard':'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂತಿರುಗಿ'},
}
const labels: Record<Language, string> = { en:'English',te:'తెలుగు',hi:'हिन्दी',ml:'മലയാളം',kn:'ಕನ್ನಡ' }
interface LanguageContextValue { language: Language; setLanguage: (language: Language) => void; t: (key: string) => string; languageLabel: string }
const LanguageContext = createContext<LanguageContextValue | null>(null)
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language,setLanguageState] = useState<Language>(() => { const saved=localStorage.getItem(KEY) as Language|null; return saved && saved in labels ? saved : 'en' })
  const setLanguage=(value:Language)=>{setLanguageState(value);localStorage.setItem(KEY,value)}
  useEffect(()=>{document.documentElement.lang=language},[language])
  const value=useMemo(()=>({language,setLanguage,languageLabel:labels[language],t:(key:string)=>translations[language][key] ?? key}),[language])
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}
export function useLanguage(){const value=useContext(LanguageContext);if(!value)throw new Error('useLanguage must be used inside LanguageProvider');return value}
