from sqlalchemy import select
from app.models import Exercise

EXERCISES = [
    {'slug': 'beginner-bodyweight-squat', 'name': 'Bodyweight Squat', 'muscle_group': 'Legs', 'equipment': 'None', 'difficulty': 'Beginner', 'sets': 3, 'reps': '10-15', 'rest_seconds': 60, 'description': 'Bodyweight Squat is a beginner movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['General Fitness', 'Fat Loss'], 'image_key': 'beginner-bodyweight-squat', 'pose_supported': True, 'pose_type': 'squat'},
    {'slug': 'beginner-glute-bridge', 'name': 'Glute Bridge', 'muscle_group': 'Legs', 'equipment': 'None', 'difficulty': 'Beginner', 'sets': 3, 'reps': '10-15', 'rest_seconds': 60, 'description': 'Glute Bridge is a beginner movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['General Fitness', 'Fat Loss'], 'image_key': 'beginner-glute-bridge', 'pose_supported': True, 'pose_type': 'glute_bridge'},
    {'slug': 'beginner-knee-push-up', 'name': 'Knee Push-Up', 'muscle_group': 'Chest', 'equipment': 'None', 'difficulty': 'Beginner', 'sets': 3, 'reps': '10-15', 'rest_seconds': 60, 'description': 'Knee Push-Up is a beginner movement for chest development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['General Fitness', 'Fat Loss'], 'image_key': 'beginner-knee-push-up', 'pose_supported': True, 'pose_type': 'pushup'},
    {'slug': 'beginner-wall-push-up', 'name': 'Wall Push-Up', 'muscle_group': 'Chest', 'equipment': 'None', 'difficulty': 'Beginner', 'sets': 3, 'reps': '10-15', 'rest_seconds': 60, 'description': 'Wall Push-Up is a beginner movement for chest development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['General Fitness', 'Fat Loss'], 'image_key': 'beginner-wall-push-up', 'pose_supported': True, 'pose_type': 'wall_pushup'},
    {'slug': 'beginner-reverse-lunge', 'name': 'Reverse Lunge', 'muscle_group': 'Legs', 'equipment': 'None', 'difficulty': 'Beginner', 'sets': 3, 'reps': '10-15', 'rest_seconds': 60, 'description': 'Reverse Lunge is a beginner movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['General Fitness', 'Fat Loss'], 'image_key': 'beginner-reverse-lunge', 'pose_supported': True, 'pose_type': 'lunge'},
    {'slug': 'beginner-step-up', 'name': 'Step-Up', 'muscle_group': 'Legs', 'equipment': 'None', 'difficulty': 'Beginner', 'sets': 3, 'reps': '10-15', 'rest_seconds': 60, 'description': 'Step-Up is a beginner movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['General Fitness', 'Fat Loss'], 'image_key': 'beginner-step-up', 'pose_supported': True, 'pose_type': 'step_up'},
    {'slug': 'beginner-bodyweight-split-squat', 'name': 'Bodyweight Split Squat', 'muscle_group': 'Legs', 'equipment': 'None', 'difficulty': 'Beginner', 'sets': 3, 'reps': '10-15', 'rest_seconds': 60, 'description': 'Bodyweight Split Squat is a beginner movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['General Fitness', 'Fat Loss'], 'image_key': 'beginner-bodyweight-split-squat', 'pose_supported': True, 'pose_type': 'split_squat'},
    {'slug': 'beginner-standing-calf-raise', 'name': 'Standing Calf Raise', 'muscle_group': 'Legs', 'equipment': 'None', 'difficulty': 'Beginner', 'sets': 3, 'reps': '10-15', 'rest_seconds': 60, 'description': 'Standing Calf Raise is a beginner movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['General Fitness', 'Fat Loss'], 'image_key': 'beginner-standing-calf-raise', 'pose_supported': True, 'pose_type': 'calf_raise'},
    {'slug': 'beginner-forearm-plank', 'name': 'Forearm Plank', 'muscle_group': 'Core', 'equipment': 'None', 'difficulty': 'Beginner', 'sets': 3, 'reps': '10-15', 'rest_seconds': 60, 'description': 'Forearm Plank is a beginner movement for core development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['General Fitness', 'Fat Loss'], 'image_key': 'beginner-forearm-plank', 'pose_supported': True, 'pose_type': 'plank'},
    {'slug': 'beginner-dead-bug', 'name': 'Dead Bug', 'muscle_group': 'Core', 'equipment': 'None', 'difficulty': 'Beginner', 'sets': 3, 'reps': '10-15', 'rest_seconds': 60, 'description': 'Dead Bug is a beginner movement for core development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['General Fitness', 'Fat Loss'], 'image_key': 'beginner-dead-bug', 'pose_supported': True, 'pose_type': 'dead_bug'},
    {'slug': 'beginner-bird-dog', 'name': 'Bird Dog', 'muscle_group': 'Core', 'equipment': 'None', 'difficulty': 'Beginner', 'sets': 3, 'reps': '10-15', 'rest_seconds': 60, 'description': 'Bird Dog is a beginner movement for core development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['General Fitness', 'Fat Loss'], 'image_key': 'beginner-bird-dog', 'pose_supported': True, 'pose_type': 'bird_dog'},
    {'slug': 'beginner-mountain-climber', 'name': 'Mountain Climber', 'muscle_group': 'Full Body', 'equipment': 'None', 'difficulty': 'Beginner', 'sets': 3, 'reps': '10-15', 'rest_seconds': 60, 'description': 'Mountain Climber is a beginner movement for full body development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['General Fitness', 'Fat Loss'], 'image_key': 'beginner-mountain-climber', 'pose_supported': True, 'pose_type': 'mountain_climber'},
    {'slug': 'beginner-high-knees', 'name': 'High Knees', 'muscle_group': 'Full Body', 'equipment': 'None', 'difficulty': 'Beginner', 'sets': 3, 'reps': '10-15', 'rest_seconds': 60, 'description': 'High Knees is a beginner movement for full body development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['General Fitness', 'Fat Loss'], 'image_key': 'beginner-high-knees', 'pose_supported': True, 'pose_type': 'high_knees'},
    {'slug': 'beginner-bodyweight-good-morning', 'name': 'Bodyweight Good Morning', 'muscle_group': 'Legs', 'equipment': 'None', 'difficulty': 'Beginner', 'sets': 3, 'reps': '10-15', 'rest_seconds': 60, 'description': 'Bodyweight Good Morning is a beginner movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['General Fitness', 'Fat Loss'], 'image_key': 'beginner-bodyweight-good-morning', 'pose_supported': True, 'pose_type': 'good_morning'},
    {'slug': 'beginner-superman', 'name': 'Superman', 'muscle_group': 'Back', 'equipment': 'None', 'difficulty': 'Beginner', 'sets': 3, 'reps': '10-15', 'rest_seconds': 60, 'description': 'Superman is a beginner movement for back development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['General Fitness', 'Fat Loss'], 'image_key': 'beginner-superman', 'pose_supported': True, 'pose_type': 'superman'},
    {'slug': 'beginner-side-plank', 'name': 'Side Plank', 'muscle_group': 'Core', 'equipment': 'None', 'difficulty': 'Beginner', 'sets': 3, 'reps': '10-15', 'rest_seconds': 60, 'description': 'Side Plank is a beginner movement for core development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['General Fitness', 'Fat Loss'], 'image_key': 'beginner-side-plank', 'pose_supported': True, 'pose_type': 'side_plank'},
    {'slug': 'beginner-chair-squat', 'name': 'Chair Squat', 'muscle_group': 'Legs', 'equipment': 'None', 'difficulty': 'Beginner', 'sets': 3, 'reps': '10-15', 'rest_seconds': 60, 'description': 'Chair Squat is a beginner movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['General Fitness', 'Fat Loss'], 'image_key': 'beginner-chair-squat', 'pose_supported': True, 'pose_type': 'chair_squat'},
    {'slug': 'beginner-incline-push-up', 'name': 'Incline Push-Up', 'muscle_group': 'Chest', 'equipment': 'None', 'difficulty': 'Beginner', 'sets': 3, 'reps': '10-15', 'rest_seconds': 60, 'description': 'Incline Push-Up is a beginner movement for chest development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['General Fitness', 'Fat Loss'], 'image_key': 'beginner-incline-push-up', 'pose_supported': True, 'pose_type': 'incline_pushup'},
    {'slug': 'beginner-crunch', 'name': 'Crunch', 'muscle_group': 'Core', 'equipment': 'None', 'difficulty': 'Beginner', 'sets': 3, 'reps': '10-15', 'rest_seconds': 60, 'description': 'Crunch is a beginner movement for core development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['General Fitness', 'Fat Loss'], 'image_key': 'beginner-crunch', 'pose_supported': True, 'pose_type': 'crunch'},
    {'slug': 'beginner-bear-plank', 'name': 'Bear Plank', 'muscle_group': 'Core', 'equipment': 'None', 'difficulty': 'Beginner', 'sets': 3, 'reps': '10-15', 'rest_seconds': 60, 'description': 'Bear Plank is a beginner movement for core development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['General Fitness', 'Fat Loss'], 'image_key': 'beginner-bear-plank', 'pose_supported': True, 'pose_type': 'bear_plank'},
    {'slug': 'beginner-dumbbell-bicep-curl', 'name': 'Dumbbell Bicep Curl', 'muscle_group': 'Arms', 'equipment': 'Dumbbell', 'difficulty': 'Beginner', 'sets': 3, 'reps': '10-12', 'rest_seconds': 60, 'description': 'A beginner-friendly dumbbell curl with controlled elbow movement.', 'cues': ['Keep elbows close to your body', 'Avoid swinging the weight', 'Lower slowly and with control'], 'common_mistakes': ['Swinging the torso', 'Moving the elbows forward', 'Dropping the weight quickly'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'beginner-dumbbell-bicep-curl', 'pose_supported': True, 'pose_type': 'bicep_curl'},
    {'slug': 'beginner-dumbbell-shoulder-press', 'name': 'Dumbbell Shoulder Press', 'muscle_group': 'Shoulders', 'equipment': 'Dumbbell', 'difficulty': 'Beginner', 'sets': 3, 'reps': '8-12', 'rest_seconds': 60, 'description': 'A beginner-friendly overhead press using light dumbbells and controlled movement.', 'cues': ['Brace your core', 'Press vertically without rushing', 'Control the lowering phase'], 'common_mistakes': ['Arching the lower back', 'Rushing the press', 'Dropping the elbows too low'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'beginner-dumbbell-shoulder-press', 'pose_supported': True, 'pose_type': 'shoulder_press'},
    {'slug': 'intermediate-dumbbell-goblet-squat', 'name': 'Dumbbell Goblet Squat', 'muscle_group': 'Legs', 'equipment': 'Dumbbell', 'difficulty': 'Intermediate', 'sets': 4, 'reps': '8-12', 'rest_seconds': 90, 'description': 'Dumbbell Goblet Squat is a intermediate movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'intermediate-dumbbell-goblet-squat', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'intermediate-dumbbell-bench-press', 'name': 'Dumbbell Bench Press', 'muscle_group': 'Chest', 'equipment': 'Dumbbell', 'difficulty': 'Intermediate', 'sets': 4, 'reps': '8-12', 'rest_seconds': 90, 'description': 'Dumbbell Bench Press is a intermediate movement for chest development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'intermediate-dumbbell-bench-press', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'intermediate-one-arm-dumbbell-row', 'name': 'One-Arm Dumbbell Row', 'muscle_group': 'Back', 'equipment': 'Dumbbell', 'difficulty': 'Intermediate', 'sets': 4, 'reps': '8-12', 'rest_seconds': 90, 'description': 'One-Arm Dumbbell Row is a intermediate movement for back development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'intermediate-one-arm-dumbbell-row', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'intermediate-dumbbell-shoulder-press', 'name': 'Dumbbell Shoulder Press', 'muscle_group': 'Shoulders', 'equipment': 'Dumbbell', 'difficulty': 'Intermediate', 'sets': 4, 'reps': '8-12', 'rest_seconds': 90, 'description': 'Dumbbell Shoulder Press is a intermediate movement for shoulders development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'intermediate-dumbbell-shoulder-press', 'pose_supported': False, 'pose_type': 'shoulder_press'},
    {'slug': 'intermediate-dumbbell-walking-lunge', 'name': 'Dumbbell Walking Lunge', 'muscle_group': 'Legs', 'equipment': 'Dumbbell', 'difficulty': 'Intermediate', 'sets': 4, 'reps': '8-12', 'rest_seconds': 90, 'description': 'Dumbbell Walking Lunge is a intermediate movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'intermediate-dumbbell-walking-lunge', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'intermediate-dumbbell-romanian-deadlift', 'name': 'Dumbbell Romanian Deadlift', 'muscle_group': 'Legs', 'equipment': 'Dumbbell', 'difficulty': 'Intermediate', 'sets': 4, 'reps': '8-12', 'rest_seconds': 90, 'description': 'Dumbbell Romanian Deadlift is a intermediate movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'intermediate-dumbbell-romanian-deadlift', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'intermediate-lat-pulldown', 'name': 'Lat Pulldown', 'muscle_group': 'Back', 'equipment': 'Machine', 'difficulty': 'Intermediate', 'sets': 4, 'reps': '8-12', 'rest_seconds': 90, 'description': 'Lat Pulldown is a intermediate movement for back development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'intermediate-lat-pulldown', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'intermediate-seated-cable-row', 'name': 'Seated Cable Row', 'muscle_group': 'Back', 'equipment': 'Cable', 'difficulty': 'Intermediate', 'sets': 4, 'reps': '8-12', 'rest_seconds': 90, 'description': 'Seated Cable Row is a intermediate movement for back development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'intermediate-seated-cable-row', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'intermediate-cable-chest-fly', 'name': 'Cable Chest Fly', 'muscle_group': 'Chest', 'equipment': 'Cable', 'difficulty': 'Intermediate', 'sets': 4, 'reps': '8-12', 'rest_seconds': 90, 'description': 'Cable Chest Fly is a intermediate movement for chest development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'intermediate-cable-chest-fly', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'intermediate-cable-face-pull', 'name': 'Cable Face Pull', 'muscle_group': 'Shoulders', 'equipment': 'Cable', 'difficulty': 'Intermediate', 'sets': 4, 'reps': '8-12', 'rest_seconds': 90, 'description': 'Cable Face Pull is a intermediate movement for shoulders development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'intermediate-cable-face-pull', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'intermediate-leg-press', 'name': 'Leg Press', 'muscle_group': 'Legs', 'equipment': 'Machine', 'difficulty': 'Intermediate', 'sets': 4, 'reps': '8-12', 'rest_seconds': 90, 'description': 'Leg Press is a intermediate movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'intermediate-leg-press', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'intermediate-seated-leg-curl', 'name': 'Seated Leg Curl', 'muscle_group': 'Legs', 'equipment': 'Machine', 'difficulty': 'Intermediate', 'sets': 4, 'reps': '8-12', 'rest_seconds': 90, 'description': 'Seated Leg Curl is a intermediate movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'intermediate-seated-leg-curl', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'intermediate-cable-triceps-pushdown', 'name': 'Cable Triceps Pushdown', 'muscle_group': 'Arms', 'equipment': 'Cable', 'difficulty': 'Intermediate', 'sets': 4, 'reps': '8-12', 'rest_seconds': 90, 'description': 'Cable Triceps Pushdown is a intermediate movement for arms development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'intermediate-cable-triceps-pushdown', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'intermediate-dumbbell-bicep-curl', 'name': 'Dumbbell Bicep Curl', 'muscle_group': 'Arms', 'equipment': 'Dumbbell', 'difficulty': 'Intermediate', 'sets': 4, 'reps': '8-12', 'rest_seconds': 90, 'description': 'Dumbbell Bicep Curl is a intermediate movement for arms development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'intermediate-dumbbell-bicep-curl', 'pose_supported': False, 'pose_type': 'bicep_curl'},
    {'slug': 'intermediate-kettlebell-swing', 'name': 'Kettlebell Swing', 'muscle_group': 'Full Body', 'equipment': 'Kettlebell', 'difficulty': 'Intermediate', 'sets': 4, 'reps': '8-12', 'rest_seconds': 90, 'description': 'Kettlebell Swing is a intermediate movement for full body development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'intermediate-kettlebell-swing', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'intermediate-barbell-back-squat', 'name': 'Barbell Back Squat', 'muscle_group': 'Legs', 'equipment': 'Barbell', 'difficulty': 'Intermediate', 'sets': 4, 'reps': '8-12', 'rest_seconds': 90, 'description': 'Barbell Back Squat is a intermediate movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'intermediate-barbell-back-squat', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'intermediate-barbell-bench-press', 'name': 'Barbell Bench Press', 'muscle_group': 'Chest', 'equipment': 'Barbell', 'difficulty': 'Intermediate', 'sets': 4, 'reps': '8-12', 'rest_seconds': 90, 'description': 'Barbell Bench Press is a intermediate movement for chest development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'intermediate-barbell-bench-press', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'intermediate-cable-lateral-raise', 'name': 'Cable Lateral Raise', 'muscle_group': 'Shoulders', 'equipment': 'Cable', 'difficulty': 'Intermediate', 'sets': 4, 'reps': '8-12', 'rest_seconds': 90, 'description': 'Cable Lateral Raise is a intermediate movement for shoulders development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'intermediate-cable-lateral-raise', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'intermediate-dumbbell-bulgarian-split-squat', 'name': 'Dumbbell Bulgarian Split Squat', 'muscle_group': 'Legs', 'equipment': 'Dumbbell', 'difficulty': 'Intermediate', 'sets': 4, 'reps': '8-12', 'rest_seconds': 90, 'description': 'Dumbbell Bulgarian Split Squat is a intermediate movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'intermediate-dumbbell-bulgarian-split-squat', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'intermediate-dumbbell-romanian-deadlift-plus', 'name': 'Dumbbell Romanian Deadlift Plus', 'muscle_group': 'Legs', 'equipment': 'Dumbbell', 'difficulty': 'Intermediate', 'sets': 4, 'reps': '8-12', 'rest_seconds': 90, 'description': 'Dumbbell Romanian Deadlift Plus is a intermediate movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'intermediate-dumbbell-romanian-deadlift-plus', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'advanced-conventional-deadlift', 'name': 'Conventional Deadlift', 'muscle_group': 'Back', 'equipment': 'Barbell', 'difficulty': 'Advanced', 'sets': 4, 'reps': '5-10', 'rest_seconds': 90, 'description': 'Conventional Deadlift is a advanced movement for back development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'advanced-conventional-deadlift', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'advanced-front-squat', 'name': 'Front Squat', 'muscle_group': 'Legs', 'equipment': 'Barbell', 'difficulty': 'Advanced', 'sets': 4, 'reps': '5-10', 'rest_seconds': 90, 'description': 'Front Squat is a advanced movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'advanced-front-squat', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'advanced-barbell-row', 'name': 'Barbell Row', 'muscle_group': 'Back', 'equipment': 'Barbell', 'difficulty': 'Advanced', 'sets': 4, 'reps': '5-10', 'rest_seconds': 90, 'description': 'Barbell Row is a advanced movement for back development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'advanced-barbell-row', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'advanced-barbell-overhead-press', 'name': 'Barbell Overhead Press', 'muscle_group': 'Shoulders', 'equipment': 'Barbell', 'difficulty': 'Advanced', 'sets': 4, 'reps': '5-10', 'rest_seconds': 90, 'description': 'Barbell Overhead Press is a advanced movement for shoulders development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'advanced-barbell-overhead-press', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'advanced-weighted-pull-up', 'name': 'Weighted Pull-Up', 'muscle_group': 'Back', 'equipment': 'Full Gym', 'difficulty': 'Advanced', 'sets': 4, 'reps': '5-10', 'rest_seconds': 90, 'description': 'Weighted Pull-Up is a advanced movement for back development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'advanced-weighted-pull-up', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'advanced-weighted-dip', 'name': 'Weighted Dip', 'muscle_group': 'Chest', 'equipment': 'Full Gym', 'difficulty': 'Advanced', 'sets': 4, 'reps': '5-10', 'rest_seconds': 90, 'description': 'Weighted Dip is a advanced movement for chest development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'advanced-weighted-dip', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'advanced-barbell-hip-thrust', 'name': 'Barbell Hip Thrust', 'muscle_group': 'Legs', 'equipment': 'Barbell', 'difficulty': 'Advanced', 'sets': 4, 'reps': '5-10', 'rest_seconds': 90, 'description': 'Barbell Hip Thrust is a advanced movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'advanced-barbell-hip-thrust', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'advanced-paused-barbell-squat', 'name': 'Paused Barbell Squat', 'muscle_group': 'Legs', 'equipment': 'Barbell', 'difficulty': 'Advanced', 'sets': 4, 'reps': '5-10', 'rest_seconds': 90, 'description': 'Paused Barbell Squat is a advanced movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'advanced-paused-barbell-squat', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'advanced-incline-barbell-bench-press', 'name': 'Incline Barbell Bench Press', 'muscle_group': 'Chest', 'equipment': 'Barbell', 'difficulty': 'Advanced', 'sets': 4, 'reps': '5-10', 'rest_seconds': 90, 'description': 'Incline Barbell Bench Press is a advanced movement for chest development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'advanced-incline-barbell-bench-press', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'advanced-barbell-romanian-deadlift', 'name': 'Barbell Romanian Deadlift', 'muscle_group': 'Legs', 'equipment': 'Barbell', 'difficulty': 'Advanced', 'sets': 4, 'reps': '5-10', 'rest_seconds': 90, 'description': 'Barbell Romanian Deadlift is a advanced movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'advanced-barbell-romanian-deadlift', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'advanced-heavy-cable-row', 'name': 'Heavy Cable Row', 'muscle_group': 'Back', 'equipment': 'Cable', 'difficulty': 'Advanced', 'sets': 4, 'reps': '5-10', 'rest_seconds': 90, 'description': 'Heavy Cable Row is a advanced movement for back development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'advanced-heavy-cable-row', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'advanced-heavy-leg-press', 'name': 'Heavy Leg Press', 'muscle_group': 'Legs', 'equipment': 'Machine', 'difficulty': 'Advanced', 'sets': 4, 'reps': '5-10', 'rest_seconds': 90, 'description': 'Heavy Leg Press is a advanced movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'advanced-heavy-leg-press', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'advanced-leg-extension', 'name': 'Leg Extension', 'muscle_group': 'Legs', 'equipment': 'Machine', 'difficulty': 'Advanced', 'sets': 4, 'reps': '5-10', 'rest_seconds': 90, 'description': 'Leg Extension is a advanced movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'advanced-leg-extension', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'advanced-lying-leg-curl', 'name': 'Lying Leg Curl', 'muscle_group': 'Legs', 'equipment': 'Machine', 'difficulty': 'Advanced', 'sets': 4, 'reps': '5-10', 'rest_seconds': 90, 'description': 'Lying Leg Curl is a advanced movement for legs development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'advanced-lying-leg-curl', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'advanced-cable-crossover', 'name': 'Cable Crossover', 'muscle_group': 'Chest', 'equipment': 'Cable', 'difficulty': 'Advanced', 'sets': 4, 'reps': '5-10', 'rest_seconds': 90, 'description': 'Cable Crossover is a advanced movement for chest development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'advanced-cable-crossover', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'advanced-heavy-dumbbell-bench-press', 'name': 'Heavy Dumbbell Bench Press', 'muscle_group': 'Chest', 'equipment': 'Dumbbell', 'difficulty': 'Advanced', 'sets': 4, 'reps': '5-10', 'rest_seconds': 90, 'description': 'Heavy Dumbbell Bench Press is a advanced movement for chest development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'advanced-heavy-dumbbell-bench-press', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'advanced-heavy-one-arm-dumbbell-row', 'name': 'Heavy One-Arm Dumbbell Row', 'muscle_group': 'Back', 'equipment': 'Dumbbell', 'difficulty': 'Advanced', 'sets': 4, 'reps': '5-10', 'rest_seconds': 90, 'description': 'Heavy One-Arm Dumbbell Row is a advanced movement for back development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'advanced-heavy-one-arm-dumbbell-row', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'advanced-barbell-curl', 'name': 'Barbell Curl', 'muscle_group': 'Arms', 'equipment': 'Barbell', 'difficulty': 'Advanced', 'sets': 4, 'reps': '5-10', 'rest_seconds': 90, 'description': 'Barbell Curl is a advanced movement for arms development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'advanced-barbell-curl', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'advanced-ez-bar-skull-crusher', 'name': 'EZ-Bar Skull Crusher', 'muscle_group': 'Arms', 'equipment': 'Barbell', 'difficulty': 'Advanced', 'sets': 4, 'reps': '5-10', 'rest_seconds': 90, 'description': 'EZ-Bar Skull Crusher is a advanced movement for arms development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'advanced-ez-bar-skull-crusher', 'pose_supported': False, 'pose_type': 'none'},
    {'slug': 'advanced-cable-crunch', 'name': 'Cable Crunch', 'muscle_group': 'Core', 'equipment': 'Cable', 'difficulty': 'Advanced', 'sets': 4, 'reps': '5-10', 'rest_seconds': 90, 'description': 'Cable Crunch is a advanced movement for core development and controlled training.', 'cues': ['Use controlled range of motion', 'Brace your core and keep alignment', 'Return to the start with control'], 'common_mistakes': ['Using momentum', 'Losing alignment', 'Moving through a painful range'], 'goal_tags': ['Muscle Building', 'Strength'], 'image_key': 'advanced-cable-crunch', 'pose_supported': False, 'pose_type': 'none'},
]

def seed_exercises(db):
    existing = {row[0]: row[1] for row in db.execute(select(Exercise.id, Exercise.slug)).all()}
    added = 0
    updated = 0
    for data in EXERCISES:
        row = db.query(Exercise).filter(Exercise.slug == data["slug"]).first()
        if row is None:
            db.add(Exercise(**data))
            added += 1
            continue
        changed = False
        # Keep existing user data, but synchronize exercise metadata that controls
        # the training engine (especially Beginner AI form checking).
        for key in ("pose_supported", "pose_type", "image_key"):
            if getattr(row, key) != data[key]:
                setattr(row, key, data[key])
                changed = True
        if changed:
            updated += 1
    if added or updated:
        db.commit()
    return added + updated
